### ISSUE TITLE
No data for sample query "Chinese activities using steel"

### ISSUE THREAD

**Issue by BenPortner** [BONSAMURAIS/BONSAI-ontology-RDF-framework#31]
Hi BONSAMURAIS,

when I visit the [SPARQL endpoint](http://odas.aau.dk/), choose the sample query `Chinese activities using steel` from the drop-down list, and press the play button, I do not get any results (just `No data available in table`). Is this the expected behavior?

Cheers
Ben

**Comment by agneta20** [comment]
Hi Ben 
We are currently updating the exiobase data in rdf format due to some previous challenges. We will be uploading the data again by this afternoon and then recheck with the queries. 
Besides this some of the queries outputs need to be correctly formatted and we are working on it. If you have prior knowledge on SPARQL do let us know. You could also support us with your expertise or feedback.

**Comment by BenPortner** [comment]
Hi @agneta20,
I've only just started to use SPARQL but I'm here to learn 😃 Is there anything specific you would like me to look into?

**Comment by kuzeko** [comment]
@IKnowLogic  can you check this?

**Comment by IKnowLogic** [comment]
@BenPortner @agneta20 @kuzeko  
The problem has been resolved.
The problem persisted since we were updating the exiobase data.
The query now returns several triples.
